### ISSUE TITLE
[BUG] - COLD FUEL RECIRC

### ISSUE THREAD

**Issue by joon44** [invernyx/md11-bugs#1088]
### Describe the bug

Cold fuel recirculation doesnt seem to do anything besides show the EAD warning message.

### Steps to reproduce

Fly with the fuel close to freezing temperature

### Expected behaviour

According to the AOM, when the tail tank reaches 8c from freezing point (in FMC its -40c), the cold fuel in the tail tank is recirculated to raise the temperature. Below I have attached a screenshot in which the temperature has dropped from -32 to -33 and the COLD FUEL RECIRC on the EAD has been for 30 minutes and there is no change in the fuel temperature in the tail tank.

Update: After 1 hour the fuel temperature in the tail tank rose to -28c so apparently something did happen but I guess its too slow then?

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/102414406/57865671-7647-44de-828b-d24ee8aa0aea)

![image](https://github.com/invernyx/md11-bugs/assets/102414406/4d2b988c-2cd2-41c0-afa0-10b28b75e0c1)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

37000

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
it never got within 5 degrees of freezing. So there was no need to start the further phase recirculation (moving fuel forward and replacing it with tank 2 fuel. There is no garuantee that the cold fuel recirc (seen in this picture pumping from tail tank to tail tank) can outpace the cool down effect, that's why there is a more powerfull phase. There is physics that simulate this, i don't see a bug here currently.
