### ISSUE TITLE
[BUG] - Parking brakes APPLY/RELEASE procedure

### ISSUE THREAD

**Issue by Dimples82** [invernyx/md11-bugs#1200]
### Describe the bug

The parking brake APPLY/RELEASE procedure is not connect with toe pedals, but it should.

### Steps to reproduce

-

### Expected behaviour

Parking brakes are set by applying full braking pressure with the toe-operated rudder pedal brakes, positioning the PARK BRAKE handle full aft, and then releasing the rudder pedals. This traps braking pressure in the system.

The parking brakes can be released by fully depressing and then releasing the toe pedals.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

Ground

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
We will only be implementing the following:
- The parking brakes can be released by fully depressing and then releasing the toe pedals.

This is because the procedure to fully apply them would not be common knowledge for most users, and we feel it may cause frustration for those users. Additionally, it would be impossible to do so if you do not have the adequate equipment (rudder pedals or a different bind entirely) to do so.

**Comment by turbofandude** [comment]
Since resolved as an option
