### ISSUE TITLE
[BUG] - Pressing the mic source button for VHF 2 sets the captains mic source to VHF 2 on his side.

### ISSUE THREAD

**Issue by Alex6511** [invernyx/md11-bugs#1263]
### Describe the bug

Pressing the mic source button for VHF 2 sets the captains mic source to VHF 2 on his side.

### Steps to reproduce

Set both radios to VHF 1, then press VHF 2 on the FO's side, and notice that the captain is now talking on VHF 2. Pressing VHF 1 again sets the captain back to VHF 1 as well. Notice that when both radios are on VHF 1, pressing VHF 3 _does not_ produce the same effect. 

### Expected behaviour

My understanding is the mic switches should not be related at all.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by pburnay-invernyx** [comment]
You'll find different approaches depending on the addon used. Independently, other high fidelity aircraft such as the TFDi Design MD-11 will also make use of their FO radio stack because there's a high number of people that enjoy flying the aircraft from the FO's perspective. Thus, they'll want to make use of the FO's radio stack.

A slightly different approach taken by a few is that they set the transmission (TX) channel to the last selected VHF Mic **without synching** the radio stacks which may cause confusion during the flight since one Mic may be set to VHF1, the other to VHF2 and you won't be sure on which channel you are transmitting without looking at the online client in use such as vpilot.

And yes, there are moments whereby it is beneficial to have two frequencies simultaneously tuned so that you may hear the comms from both (but while only transmitting on one, of course).
