### ISSUE TITLE
[BUG] - Fuel page - Crosses not turning white when fuel is in the tanks 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1299]
### Describe the bug

Fuel page - Crosses not turning white when fuel is in the tanks 

### Expected behaviour

To have the crosses white to the amount of fuel that is in the tanks 

### Evidence

![Schermopname (599)](https://github.com/invernyx/md11-bugs/assets/150957609/1936a985-6d5c-42f9-bcc7-06383214a187)
![Schermopname (540)](https://github.com/invernyx/md11-bugs/assets/150957609/ecd1908c-a247-4c7e-a649-8d04588b916f)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by fugotaro** [comment]
To add to that the cross for the ballast fuel value is missing

**Comment by GenericNerd** [comment]
The fuel synoptic follows the convention outlined in Section 2.3.5 of the Honeywell Manual for failure annunciation. This details that a AMBER "X"s or annunciations signify a loss of data. This is what the yellow "X" signifies in each fuel tank during the annunciator test.
Section 2.3.5 at no point makes reference of a white "X". This leads us to believe that this is only a result of the way the image was taken, rather than the "X"s being made white or lighter.
