### ISSUE TITLE
[BUG] - Engine start up & fan blade animation is too quick

### ISSUE THREAD

**Issue by davidnorfolk96** [invernyx/md11-bugs#1376]
### Describe the bug

See above 

### Steps to reproduce

Do a normal engine start up, Look at the fan blades & you'll see they spin too quick. 

### Expected behaviour

Engines fan blades to start spinning slower & then gradually speed up. See video below

### Evidence

https://www.youtube.com/watch?v=7CJE7m_J7fY

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
The current implementation of the fan blades do not allow for as of smooth transitions as in a real life blade, as at a certain RPM a blurred and slow texture appears. MSFS does not have proper motion blur with engine blades, at least not in the default Asobo engine XML template. I have re-rendered the engine atlas but it will not be perfectly smooth due to the aforementioned reason. This bug is sort-of half fixed because of the limitations imposed by the engine template.
