### ISSUE TITLE
[BUG] - Cannot reenter approach data after a missed approach

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#1595]
### Describe the bug

After a missed approach into Seoul South Korea, I went to try and enter in the approach data in the FMS but was unable to even after hitting insert. I had to manually vector myself back onto the approach and LOC.

### Steps to reproduce

Fly any missed approach and try to enter in the approach back into the FMS

### Expected behaviour

To have way to navigate back to the airport during a missed approach.

### Evidence

This was after I had entered in the runway back into the FMC and hit INSERT.
![20240707100455_1](https://github.com/invernyx/md11-bugs/assets/150947401/5ceaa432-9fb7-4a43-b0de-cd9b4e28fcd5)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Approach

### Altitude

N/A

### Departure

N/A

### Arrival

RKSI

### Cruise level

N/A

### ZFW

N/A

### CG

N/A

### Fuel

N/A

### Cost index

N/A

### Route

N/A

### Location

RKSI

### Agreement

- [X] Yes

**Comment by TheEvilToaster** [comment]
The destination waypoint is gone, I'm assuming because the aircraft believes you've flown over it --- Not sure if this is correct behaviour though ----.

You need to reenter the destination airport again into the flightplan page next to "END OF FLT PLN" and then will the arrival page show up and you can select the approach again.

**Comment by TheFightingRaven** [comment]
this is correct behaviour. Manuals prescribe to enter a new waypoint as a direct then entering the star from there
