### ISSUE TITLE
[BUG] - 250 KTS Below 10k not honoured when CRZ level is below 10k

### ISSUE THREAD

**Issue by KJA1582** [invernyx/md11-bugs#1613]
### Describe the bug

Cruising at a crz level below 10k does not restrict ECON speed to 250kts

### Steps to reproduce

CRZ below 10k

### Expected behaviour

ECON speed should be capped to 250kts below 10k

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/2170028/182d0b82-7837-4e33-8abc-79224177310e)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

8000ft

### Departure

EDDM

### Arrival

EDDM

### Cruise level

FL080

### ZFW

112.7t

### CG

25.9%

### Fuel

13.8t

### Cost index

80

### Route

EDDM to EDDM, No SID, No STAR, ILS26L OTT Transition

### Location

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
Is it capped to 250 by FMS SPD (i.e. the AP) or would ECON itself in the PERF page show under 250?

**Comment by KJA1582** [comment]
That's a good question, one an SME ought to check (I've not found any mentionings of what it does in the docs I have, a sub 10k CRZ is rather rare).

Either way, it should definitevly cap at 250 or Min clean like it does on CLB.

**Comment by GR1MMly** [comment]
Adding discussion from discord to here. Will have to do some more digging in FMS logic when I have the time to see if I can dig up a better answer, but from the hip the speed restrictions (250/10000) are in the CLB and DES modes. I'm not aware of a cruise "limit" (outside structural/configuration limits) that can be set in CRZ.

A pitfall of cruising below 10k very well may be that you are the speed control. At least until I can locate data otherwise.

**Comment by KJA1582** [comment]
Fair point, but it'd be the only AC I know of (within the sim) that would do so (unless I completely forgot the 737/777/320 behaviour which very well might be)
