### ISSUE TITLE
[BUG] - Fuel burn performance (MD-PERF-2)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#266]
### Describe the bug

At cruise FL350, GW=420k lb, STD day temp, no wind, PACKS on ECON; no Anti-Ice the fuel flow per engine is (1)2580lb/hr at M0.76; (2)2667lb/hr at M0.78; (3)2755lb/hr at M0.80; (4)3042lb/hr at M0.82; (5)3307lb/hr at M.84.

### Steps to reproduce

see descrip

### Expected behaviour

S/B much higher fuel flow per engine at these various speeds as follows (1)4880lb/hr; (2)4650lb/hr; (3)4600lb/hr; (4)4600lb/hr; (5)4700lb/hr
NOTE: for reference, the following are fuel flows at FL390; M0.76 4730lb/hr; M0.80 5120lb/hr; M0.84 5290lb/hr

Also, I checked these numbers against the PMDG MD11 in FSX, and they matched withing 5%

### Evidence

These numbers came from flight test data

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Cruise

### Altitude

FL350

### Agreement

- [X] Yes

**Comment by uwiuke** [comment]
I could confirm the behaviour - I fly a longhaul-flight right now - (LIMC - WSSS - 5500 NM). Actually I flew 8 hours and I only have used fuel of 90.000 lbs - it's an average fuel flow (with climbing to FL330) of roughly 11.000 lbs/hr.
At FL 330 fuel flow ist between 9000 - 9300 lbs/hr for all 3 engines.
With this fuel burn I could fly more than 24 hours

**Comment by turbofandude** [comment]
This actually a two part issue. Part 1 was that the fuel used value on the SD was shown in gallons (incorrectly) and the fuel flow on the EAD was shown in pounds regardless of the unit setting. Due to this, the flight dynamics were based on the **displayed** values, causing them to be wrong. The code portion of the bug is fixed and I am working with Martyn to get the flight dynamics corrected.
