### ISSUE TITLE
[BUG] - UPS Livery unable to save change to round gauges

### ISSUE THREAD

**Issue by Wise87** [invernyx/md11-bugs#322]
### Describe the bug

Went to EFB to change the engine display from tape to round but EFB wasn't saving the settings.

### Steps to reproduce

Went to EFB to change the engine display from tape to round but EFB wasn't saving the settings. Had to edit the UPS Livery option file from True to False to get the gauges to stay round. Also when hitting SAVED, the save dialog did not pop up like it does in the out EFB pages. 

### Expected behaviour

EFB should save options selected. 

### Evidence

None

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by CaptainMac2336** [comment]
I have run across this; try clicking a little closer to the top right hand corner of the "Save" box and it seems to take. You will know when it saves because you will get a message in the lower right corner of the EFB display. The click spot seems to just be a little off center on that page. Give it a try and let everyone here know if that worked for you. I had to click around a few times to find it.

**Comment by Wise87** [comment]
Thanks for the info. I'll try it out when I get home today.

**Comment by TheFightingRaven** [comment]
does this still persist?

**Comment by Wise87** [comment]
Sorry, yes it works now. I followed the suggestions.Sent from my iPhoneOn Nov 10, 2023, at 14:07, TheFightingRaven ***@***.***> wrote:﻿
does this still persist?
