### ISSUE TITLE
[BUG] - Throttle Test Locks and crashes sim

### ISSUE THREAD

**Issue by Krythor** [invernyx/md11-bugs#359]
### Describe the bug

In Final Cockpit Preperation, Moving throttle before engine start locks sim

### Steps to reproduce

Fianl Cockpit Preparation Checklist Before engine start, Moving throttle forward and back Locks MSFS and causes a CTD

### Expected behaviour

Betty shouyld say something as part of test.

### Evidence

![locked](https://github.com/invernyx/md11-bugs/assets/150379503/8ac73026-3e7b-432b-b16c-699ba5afb7c9)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

Yes

### Phase of flight

Pre-flight

### Altitude

0 AGL

### Agreement

- [X] Yes

**Comment by Hawks1326** [comment]
Glad to see someone else experience this too!!! I have the Honeycomb Bravo throttle quadrant set up in a engine 1 3 2 axis config (via the in sim controls menu). Anytime I attempt to advance the throttles (after startup or even prior to startup), I end up with the sim hanging and need to force close MSFS as the sim won’t CTD. Disconnecting and reconnecting the Bravo Throttle quadrant does nothing either. I have to use Task Manager in order to quit the sim. Might attempt to reconfigure my Bravo Throttle Quadrant again when I have some more free time to see if it’s a binding issue.

**Comment by Hawks1326** [comment]
Did you happen to find a work around for this per chance? Or will I be stuck until a fix is found?

**Comment by Krythor** [comment]
Skip this step before your engines are running

**Comment by Hawks1326** [comment]
Thanks for the response! I still had it post engine start when testing out the issue. Wonder if I’m missing something in the checklist or if it’s my throttle config causing this.

**Comment by turbofandude** [comment]
This sould have bene resolved quite some time ago.

**Comment by CptUnicorn** [comment]
A  bit late to the party on this one, but I do a config check before and after engine start and not once have I had a CTD with the honeycomb throttles. But good to know that it may cause a crash.

**Comment by turbofandude** [comment]
> A bit late to the party on this one, but I do a config check before and after engine start and not once have I had a CTD with the honeycomb throttles. But good to know that it may cause a crash.

It... can't - the bug is resolved.
