### ISSUE TITLE
[SUGGESTION] - Let us control the MCP and other push/pull knobs via secondary/tertiary cockpit interaction

### ISSUE THREAD

**Issue by HaDeSMonsta** [invernyx/md11-bugs#485]
### Describe the bug

Let us control the knobs via secondary/tertiary cockpit interaction, like for example the fenix does, that would be better than holding and dragging the mouse in my opinion. Different to the current solution you can rebind it in the settings to what you like.

### Steps to reproduce

// It's a suggestion

### Expected behaviour

Push/pull knobs via secondary/tertiary cockpit interaction

### Evidence

![image](https://github.com/invernyx/md11-bugs/assets/122306185/16727f7e-301e-49ea-864d-1c8a394e9a9c)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by dr71205** [comment]
Or just a left click = push and right click = pull or something anything but this drag which requires such percision that it doesnt work half the time

**Comment by PointBlank66** [comment]
> anything but this drag which requires such percision that it doesnt work half the time

That is the exact same problem I am experiencing with the current way of interacting with the MCP knobs. 
I would also like to see to have clickspots for the knobs in the MCP to change their modes instead of just having pull them, something like in this video
https://github.com/invernyx/md11-bugs/assets/4239471/10bb6085-29fb-4b9a-b873-aaec0621a219

**Comment by TheFightingRaven** [comment]
will be solved in a different manner
