### ISSUE TITLE
[BUG] - Missing textures (cockpit door frames, rear doors freighter)

### ISSUE THREAD

**Issue by alxcpt** [invernyx/md11-bugs#499]
### Describe the bug

Missing textures (freighter)

### Steps to reproduce

Load up any freighter livery. Take a look at the intakes, the cockpit windows and and door 4L and R.

### Expected behaviour

Textures should appear as they are assigned in the model (here the cockpit textures)
![Screenshot 2023-11-12 170134](https://github.com/invernyx/md11-bugs/assets/150608109/4b8707e7-3153-4bcf-bddb-bbbbbc2f9afb)

### Evidence

![Screenshot 2023-11-12 170250](https://github.com/invernyx/md11-bugs/assets/150608109/423e59fd-4e5b-431e-ad30-89731b846fa1)
![Screenshot 2023-11-12 170550](https://github.com/invernyx/md11-bugs/assets/150608109/2c7f4a06-d409-48cc-b044-0a3a93bcee17)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by FreakyD777** [comment]
needs title

**Comment by arwasairl** [comment]
This is not possible without the paintkit. The COMP maps is inhibiting this. Editing the COMP maps require the original substance painter project files, which are not available at the moment until we publish the paintkit. Otherwise, the UV is correct and there are no overlapping geometry in the areas you have highlighted.
