### ISSUE TITLE
[BUG] - IRS go out on align

### ISSUE THREAD

**Issue by CptUnicorn** [invernyx/md11-bugs#571]
### Describe the bug

Flashing NAV lights on the overhead. Once you move, the IRS will fall out of alignment

### Steps to reproduce

Load in C&D, set up just as you normally do.

### Expected behaviour

NAV lights should be flashing out of sync and once you start moving, the PFD and ND will go blank and show no alignment. NOTE: I did press ALIGN IRS in the FCU.

### Evidence

https://medal.tv/games/microsoft-flight-simulator/clips/1E7NTJlLAe-qfI/d133771b2lwd?invite=cr-MSxHTUIsMTkzNzg2ODc5LA

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Phase of flight

Pre-flight

### Altitude

N/A

### Agreement

- [X] Yes

**Comment by turbofandude** [comment]
What is your default scenario setting? Do you always start C&D or do you have last state enabled?

**Comment by CptUnicorn** [comment]
> What is your default scenario setting? Do you always start C&D or do you have last state enabled?

Default state is Cold and Dark. I haven't played with the panel states yet.

**Comment by Gazguzzler** [comment]
I am also experiencing this exact issue since changing the IRS Align Time option from Realistic to Instant. I have reset to realistic and I have also uninstalled / reinstalled the aircraft but still happening. My a/c state has not been changed and is defaulted to C&D. In fact I am unable to load the different a/c states as it ignores my selection when clicking anywhere in the highlighted box. The exception is that I can change the Set as default flag to each state but the a/c allows loads C&D on restart. I am unable to fly the a/c due to these issues.

**Comment by Gazguzzler** [comment]
After multiple uninstalling and re-installing attempts using the TFDi install manager I ended up reinstalling the first software release exe. file, started up the sim and verified that the IRS alignment was OK.  I then uninstalled the first released version and reinstalled the current version using the install manager. The issue with the IRS alignment has now resolved itself and I am able to fly once more.
