### ISSUE TITLE
[BUG] - Logo light leak (MD-GEN-7)

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#582]
### Describe the bug

At night, the logo light leaks through the engine 2 cowl and is visible inside the inlet duct

### Expected behaviour

no leak

### Evidence

![FlightSimulator_2023_11_17_19_42_01_055](https://github.com/invernyx/md11-bugs/assets/148836830/6e221257-fcd4-42d1-a83c-e41a1036db70)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
This is not possible to fix from my end. MSFS (and every game that isn't ray traced) draws light first then shadows. This becomes a problem when the normals of an object become opposites to the ray of the light source, even when it's a part of an object that has it's normals parallel to the ray of the light source. There are only two solutions, change the position of the light to make it's ray direction not cross any internal faces (not possible since logo light HAS to be in a specific place) or reduce its intensity (not possible because it will make the logo light nearly invisible).

![image](https://github.com/invernyx/md11-bugs/assets/48654776/c6c3a8e4-64fc-4a4f-9e5e-bd219e6103e7)

A custom shader / routine for the lights are required in order to cast shadows correctly as MSFS does not do this on it's own, nor does it have ray tracing capabilities.
