### ISSUE TITLE
[BUG] - Central landing gear’s effects

### ISSUE THREAD

**Issue by Douglas-McCormick** [invernyx/md11-bugs#842]
### Describe the bug

Central landing gear’s effects will still display when it is not extended.

### Expected behaviour

Central landing gear’s effects will still display when it is not extended. The same issue 
occurred once in PMDG’s MD-11 product 10 years ago, that’s why I have noticed it.
It is on all versions of MD11

### Evidence

![2024-1-5_1-54-31-752](https://github.com/invernyx/md11-bugs/assets/104307400/20bbb698-dc94-4b82-b30d-e0ea1831088d)
![2024-1-5_1-54-35-677](https://github.com/invernyx/md11-bugs/assets/104307400/50f99a86-ecc4-4476-a74e-1bf6fe085607)
![2024-1-5_1-54-39-55](https://github.com/invernyx/md11-bugs/assets/104307400/f89032e8-a769-4eae-a164-cbaa56401533)

### Simulator

P3Dv4

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
P3D does not have a writeable AUX GEAR variable within it's simulator, so the AUX GEAR is actually mapped to either the left or right main gears. As a result, visual effects tied to those sections will be displayed as the center gear is copying variable data from the left gear, due to the aforementioned reason. 

There are no plans to fix this at the moment as the only solution to this is to completely rewrite a completely custom ground, wheel, and suspension system. Making a new system like this will take many weeks and especially considering that these changes will most likely require an external base to run these simulations, it is wholly impractical at the moment to start this feature to fix this bug.

MSFS does not have this issue as the AUX GEAR variable is writeable unlike in P3D.
