### ISSUE TITLE
[BUG] - Flight Control Surface Positions in Hangar Menu View

### ISSUE THREAD

**Issue by FreakyD777** [invernyx/md11-bugs#867]
### Describe the bug

When in the hangar menu view, the primary flight control surfaces are katty whompus.

### Expected behaviour

All primary flight control surfaces should be in the nuetral position in this "showroom" type hangar menu view.

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Aircraft Type

Passenger GE

### Agreement

- [X] Yes

**Comment by arwasairl** [comment]
The WASM gauge is not loaded in the hangar view, which is what drives animations. This can be fixed by setting frame 0 to neutral, however, due to how many animations there are, it isn't worth the effort to make changes to all our animations and offset our frames in code by 1 just for the hangar view.

**Comment by FreakyD777** [comment]
OK, but all your competitors don't have this problem (IniBuilds, PMDG, JustFlight).  So a user may see this and think low quality or lack of attention to detail.

**Comment by arwasairl** [comment]
All of our competitors also don't do simultaneous development for P3D of the same aircraft. Unfortunately, it is entirely too late to change this as it isn't as trivial as moving keyframes by 1. The model animation tags and code also need to be incremented.
